# Generated by Django 4.0.4 on 2022-05-10 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_rename_teacher_student_teachers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['group'], 'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
    ]
